config/routes.rb
Rails.application.routes.draw do
  root   'tasks#index'
  resources :tasks, only: [:new, :create, :show, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    enum status: {
        opened: 0,
        in_progress: 1,
        finished: 2,
      }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def index
    @tasks =  Task.all
  end
  
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    if @task.save
      flash[:success] = 'task created successfully'
      redirect_to task_path(@task)
    else
      flash.now[:danger] = 'Failed to create a new task'
      render 'new'
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def tasks_params
    params.require(:task).permit(:title, :status, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TasksApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/index.html.erb
<section class="all-events"> 
    <h1>ALL Tasks</h1>
    <% @tasks.each do |task| %>
    <div>
        <h1><%= task.title %></h1>
        <p><%= task.status %></p>
        <p><%= task.description %></p>
    </div>
    <% end %>


    <div id='create-task'>
        <%= link_to "Create Task", new_task_path %>
    </div>
</section> 

app/views/tasks/new.html.erb
<section class="create-event">
<h1>Create a Task</h1>
<%= form_for(@task, url: tasks_path) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :status %>
      <%= f.select :status, :collection => Task.statuses.keys.to_a %>
      <%= f.label :description %>
      <%= f.text_area :description, cols: 20, rows: 20 %>
      <%= f.submit 'Create Task' %>
<% end %>
</section>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<h1><%= @task.title %></h1>
<p>Status: <%= @task.status %></p>
<p>Description: <%= @task.description %></p>

    <div>
        <%= link_to "Go to index", tasks_path %>
    </div>